config/routes.rb
Rails.application.routes.draw do

	root 'posts#index'

  get 'about' => 'static_pages#about'

  resources :posts, only: [:index]

  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :users, only: [:show, :index] do
  	resources :posts, except: [:index]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user

	# To set number of items on page in index (pagination)
	self.per_page = 10

	has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>", :large => "500x500>" }
	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_user, except: [:index]
  before_action :set_post, only: [:edit, :update, :destroy, :show]

  def index
  	@posts = Post.all.order("created_at desc").paginate(page: params[:page])
  end

  def show
  end

  def new
  	@post = @user.posts.build
  end

  def create
  	@post = @user.posts.build(post_params)
  	if @post.save
  		redirect_to user_path(@user)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @post.update(post_params)
  		redirect_to user_path(@user)
  	else
  		render :edit
  	end
  end

  def destroy
  	@post.destroy
  	redirect_to user_path(@user)
  end

  private

  	def set_user
  		@user = User.find(params[:user_id])
  	end

  	def set_post
  		@post = Post.find(params[:id])
  	end

  	def post_params
  		params.require(:post).permit(:title, :description, :price, :location, :is_sold, :created_at, :photo)
  	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:username, :email, :password, 
																 :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:username, :email, :password, 
																 :password_confirmation, :current_password)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container page-top">
    <%= link_to "Anne's List", root_path, class: "navbar-brand" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path, class: "nav-text" %></li>
        <li><%= link_to "About", about_path, class: "nav-text" %></li>
        <% if user_signed_in? %>
        	<li><%= link_to "Profile", user_path(current_user), class: "nav-text" %></li>
        	<li><%= link_to "Users", users_path, class: "nav-text" %></li>
        	<li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-text"  %></li>
        <% else %>
        	<li><%= link_to "Sign Up", new_user_registration_path, class: "nav-text"  %></li>
        	<li><%= link_to "Log In", new_user_session_path, class: "nav-text"  %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>| Anne's List |</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
	<div class='container main'>
	  <p class="notice"><%= notice if notice%></p>
	  <p class="alert"><%= alert if alert %></p>
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for [@user, @post], :html => {:multipart => true} do |f| %>

	<%= f.text_field :title, placeholder: "Title", class: "form-fields"%><br>

	<%= f.text_field :price, placeholder: "$0.00", class: "form-fields" %><br>

	<%= f.text_field :location, placeholder: "Location", class: "form-fields" %><br>

	<%= f.text_area :description, placeholder: "Description", class: "form-fields" %><br>

	<div class="photo-upload-box">
		<%= f.label :photo %>
		<%= f.file_field :photo %>
	</div>

	<%= f.submit "Submit", class: "btn btn-success btn-lg user-button" %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Ad</h1>

<%= render 'posts/form' %>

<%= link_to 'Back', user_path(@user), class: "btn btn-success btn-lg user-button" %>

app/views/posts/index.html.erb
<div class="post-table">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Title</th>
				<th>Price</th>
				<th>Location</th>
				<th>User</th>
				<th>Date Posted</th>
				<th>Photo (if available)</th>
			</tr>
		</thead>
		<tbody class="table-list">   
			<% @posts.each do |post|%>
				<tr>
					<td class="col-md-3"><%= link_to post.title, user_post_path(post.user, post) %></td>
					<td class="col-md-2"><%= number_to_currency(post.price) %></td>
					<td class="col-md-2"><%= post.location %></td>
					<td class="col-md-1"><%= link_to post.user.username, user_path(post.user) %></td>
					<td class="col-md-2"><%= post.created_at.strftime("%m/%d/%Y") %></td>
					<% if post.photo.file? %>
						<td class="col-md-2"><%= image_tag post.photo.url(:thumb), class:"index-image" %>
					<% else %>
						<td class="col-md-2"> </td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>New Ad</h1>

<%= render 'posts/form' %>

<%= link_to 'Back', user_path(@user), class: "btn btn-success btn-lg user-button" %>

app/views/posts/show.html.erb
<h1><%= @post.title %> - <%= number_to_currency(@post.price) %></h1>
<h3>Location: <%= @post.location %></h3>
<% if @post.photo.file? %>
	<%= image_tag @post.photo.url(:medium) %>
<% end %>
<p><%= @post.description %></p>
<h4>Listed by: <%= link_to @post.user.username, user_path(@post.user) %></h4>
<h4>Contact info: <%= mail_to @user.email %></h4>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
	<ul class="user-list">
		<li><%= user.username %> - <%= link_to 'User Page', user_path(user), class: "btn btn-success btn-default user-button"%></li>
	</ul>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<% if current_user == @user %>
	<%= link_to 'Edit Profile', edit_user_registration_path(@user), class: "btn btn-success btn-default user-button" %>
<% else %>
	<h3>Contact: <%= mail_to @user.email %></h3>
<% end %>

<div>
	<table class="table table-striped">
		<thead>
			<tr>
				<% if current_user == @user %>
					<th colspan="2", class="table-header"><h3>Your Ads<h3></th>
				<% else %>
					<th colspan="2", class="table-header"><h3><%= @user.username.camelcase %>'s Ads<h3></th>
				<% end %>
			</tr>
			<tr>
				<th>Title</th>
				<th>Price</th>
				<% if current_user == @user %>
					<th>Edit Post</th>
					<th>Delete Post</th>
				<% end %>
				<th>Photo (if available)</th>
			</tr>
		</thead>
		<tbody class="table-list">   
			<% @user.posts.each do |post| %>
				<tr class="show-table">
					<td><%= link_to post.title, user_post_path(post.user, post) %></td>
					<td><%= number_to_currency(post.price) %></td>
					<% if current_user == @user %>
						<td><%= link_to 'Edit', edit_user_post_path(@user, post), class: "btn btn-success btn-default user-button" %></td>
						<td><%= link_to 'Delete', user_post_path(@user, post), method: :delete, class: "btn btn-success btn-default user-button" %></td>
					<% end %>
					<% if post.photo.file? %>
						<td><%= image_tag post.photo.url(:thumb) %></td>
					<% else %>
						<td> </td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<% if current_user == @user %>
	<%= link_to 'New Post', new_user_post_path(@user), class: "btn btn-success btn-default user-button" %>
<% end %>